# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(user_id: 't201701', name: '吉村先生', password: '123', flg: 0, annual: 2017, authority: 1)
User.create(user_id 's20161414', name: '野々村幸彦', password: '123', flg: 0, annual: 2016, authority: 2)
User.create(user_id 's20161415', name: '樋野拓人', password: '123', flg: 0, annual: 2016, authority: 2)
User.create(user_id 's20161406', name: '伊藤陸', password: '123', flg: 0, annual: 2016, authority: 2)
User.create(user_id 'g2016', name: 'ゲストユーザー', password: '123', flg: 0, annual: 2016, authority: 3)


EeReport.create(id: 10, reporting_date: '2018-09-01', student_class: 4, student_number: 1, student_id: 's20171401', school_name: '出雲大学', s_faculty_name: '理学部', s_department_name: '理学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '島根県出雲市大津2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: 'とても難しかったです', g_impressions: '疲れました', recommended_form: 1, approval_flg: 0)
EeReport.create(id: 11, reporting_date: '2018-09-01', student_class: 4, student_number: 2, student_id: 's20171402', school_name: '山大学', s_faculty_name: '法学部', s_department_name: '法学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '島根県松江市大津2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: '簡単です', g_impressions: '疲れました', recommended_form: 1, approval_flg: 1)
EeReport.create(id: 12, reporting_date: '2018-09-01', student_class: 4, student_number: 3, student_id: 's20171403', school_name: '海大学', s_faculty_name: '薬学部', s_department_name: '薬剤学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '北海道十勝2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: 'とても難しかったです', g_impressions: '疲れました', recommended_form: 1, approval_flg: 0)
EeReport.create(id: 13, reporting_date: '2018-09-01', student_class: 4, student_number: 4, student_id: 's20171404', school_name: '土大学', s_faculty_name: '看護学部', s_department_name: '看護学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '北海道十勝2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: 'とても難しかったです', g_impressions: '疲れました', recommended_form: 1, approval_flg: 0)
EeReport.create(id: 14, reporting_date: '2018-09-01', student_class: 4, student_number: 5, student_id: 's20171405', school_name: '火大学', s_faculty_name: '経済学部', s_department_name: '経済学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '北海道十勝2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: 'とても難しかったです', g_impressions: '疲れました', recommended_form: 1, approval_flg: 0)
EeReport.create(id: 15, reporting_date: '2018-09-01', student_class: 4, student_number: 6, student_id: 's20171406', school_name: '水大学', s_faculty_name: '文学部', s_department_name: '文学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '北海道十勝2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: 'とても難しかったです', g_impressions: '疲れました', recommended_form: 1, approval_flg: 0)
EeReport.create(id: 16, reporting_date: '2018-09-01', student_class: 4, student_number: 7, student_id: 's20171407', school_name: '闇大学', s_faculty_name: '教育学部', s_department_name: '教育学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '北海道十勝2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: 'とても難しかったです', g_impressions: '疲れました', recommended_form: 1, approval_flg: 0)
EeReport.create(id: 17, reporting_date: '2018-09-01', student_class: 4, student_number: 8, student_id: 's20171408', school_name: '光大学', s_faculty_name: '外国語学部', s_department_name: 'フランス文学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '北海道十勝2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: 'とても難しかったです', g_impressions: '疲れました', recommended_form: 1, approval_flg: 0)
EeReport.create(id: 18, reporting_date: '2018-09-01', student_class: 4, student_number: 9, student_id: 's20171409', school_name: '神大学', s_faculty_name: '農学部', s_department_name: '農学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '北海道十勝2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: 'とても難しかったです', g_impressions: '疲れました', recommended_form: 1, approval_flg: 0)
EeReport.create(id: 19, reporting_date: '2018-09-01', student_class: 4, student_number: 10, student_id: 's20171410', school_name: 'アンデット族大学', s_faculty_name: '医学部', s_department_name: '医学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '北海道十勝2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: 'とても難しかったです', g_impressions: '疲れました', recommended_form: 1, approval_flg: 0)
EeReport.create(id: 20, reporting_date: '2018-09-01', student_class: 4, student_number: 11, student_id: 's20171411', school_name: '植物族大学', s_faculty_name: '歯学部', s_department_name: '歯学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '北海道十勝2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: 'とても難しかったです', g_impressions: '疲れました', recommended_form: 1, approval_flg: 0)
EeReport.create(id: 21, reporting_date: '2018-09-01', student_class: 4, student_number: 12, student_id: 's20171412', school_name: '魚族大学', s_faculty_name: '音楽学部', s_department_name: '音楽学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '北海道十勝2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: 'とても難しかったです', g_impressions: '疲れました', recommended_form: 1, approval_flg: 0)
EeReport.create(id: 22, reporting_date: '2018-09-01', student_class: 4, student_number: 13, student_id: 's20171413', school_name: '鮪大学', s_faculty_name: '理工学部', s_department_name: '理工学科', test_day: '2018-08-19', postal_code: 6990513, street_address: '北海道十勝2525', examination_hall: '貴校', result_publication_date: '2018-08-20', entrance_form: 2, r_self: true, t_subject_japanese: 50, t_subject_math: 50, t_subject_society: 50, t_subject_science: 50, t_subject_english: 50, g_q_contents: 'とても難しかったです', g_impressions: '疲れました', recommended_form: 1, approval_flg: 0)
EeReport.create( reporting_date: '2017-10-17', student_class: 4, student_number: 12, 's20161414', school_name: '大阪成蹊短期大学', s_department_name: '幼児教育学科', test_day: '2017-10-14' street_address: '大阪府大阪市東淀川区相川 3-10-62', examination_hall: '大阪成蹊短期大学, 'result_publication_date: '2017-10-26', entrance_form: 2, recommended_group:2, r_self: true, recommended_form: 2, i_q_contents '志望理由、入学して頑張りたいこと、大阪に来たことがあるか、当日、誰と来たか、商業高校からなぜ保育に道を選んだのか、一人暮らしで家庭学習時間をどのようにとるか、オープンキャンパスでは何をしたか（体験授業）', r_impression '練習していないことも聞かれましたが、対応できました。', approval_flg: 0)
EeReport.create( reporting_date: '2017-12-11', student_class: 4, student_number: 12, 's20161414', school_name: '大阪健康福祉短期大学　松江キャンパス', s_department_name: '保育・幼児教育学科', test_day: '2017-12-09' street_address: '島根県松江市学園南1丁目15-10', examination_hall: '島根総合福祉専門学校 松江学園南キャンパス, 'result_publication_date: '2017-12-16', entrance_form: 2, recommended_group:2, r_self: true, recommended_form: 2, i_q_contents '志望理由、なりたい保育士とその理由、事故PR、楽しかったこと、つらかったこととそれをどう乗り越えたか、気になったこと、印象に残っていることピアノの経験、不安なこと、「面接時間２０分」', r_impression '面接官の方がうなずきながら聞いてくださったので、リラックスして質問に答えることができました。とても話しやすい雰囲気でした', approval_flg: 0)
EeReport.create( reporting_date: '2017-11-13', student_class: 4, student_number: 12, 's20161414', school_name: '大阪経済大学', s_faculty_name: '経済学部', s_department_name: '経済学科', test_day: '2017-11-11' street_address: '大阪府大阪市東淀川区大隅2-2-8', examination_hall: '大阪経済大学, 'result_publication_date: '2017-11-18', entrance_form: 2, recommended_group:2, r_self: true, recommended_form '「書類選考」＋小論文＋試験', e_contents '人間の離農を上回るAI(人口知能について)', w_contents '新聞の記事「新風 Silicon Vaiiey AI開発 多様な視点で」の一部の文を要約する（300文字以内）、問題文を読み、人工知能（AI）全盛期はどのような社会になるのが人々にとって理想か、自分の考えを述べる。（500文字以内） d', r_impression '小論文は先生から指導を受けたおかげで、困ることはありませんでした。しかし、商工系ということもあり工業系の知識がもう少し必要だと思いました。', approval_flg: 0)

EtReport.create(id: 10,reporting_date: '2018-09-01', student_class: 4, student_number: 1, student_id: 's20171401', job_category: '銀行員', office_name: '山陰合同銀行',job_vote_number: 132, introduction_number: 1, test_day: '2018-08-19', postal_code: 6990623, street_address: '島根県出雲市斐川町上直江2525', examination_hall: '山陰合同銀行本社', examinees_count_man: 1, examinees_count_woman: 1, selection_method: 1, s_method_writing: true, s_method_appropriate: false, s_method_interview: false, s_method_composition: false, s_method_physical: false, t_subject_japanese: 50, writing_test_contents: '余裕です', other_coment: '頑張ってください', approval_flg: 0)
EtReport.create(id: 11,reporting_date: '2018-09-01', student_class: 4, student_number: 2, student_id: 's20171402', job_category: 'パイロット', office_name: 'NASA',job_vote_number: 132, introduction_number: 1, test_day: '2018-08-19', postal_code: 6990623, street_address: '米国県フロリダ州2424', examination_hall: 'NASA', examinees_count_man: 1, examinees_count_woman: 1, selection_method: 1, s_method_writing: true, s_method_appropriate: false, s_method_interview: false, s_method_composition: false, s_method_physical: false, t_subject_japanese: 50, writing_test_contents: '余裕です', other_coment: '頑張ってください', approval_flg: 0)
EtReport.create(id: 12,reporting_date: '2018-09-01', student_class: 4, student_number: 3, student_id: 's20171403', job_category: '教師', office_name: '出雲商業高校',job_vote_number: 132, introduction_number: 1, test_day: '2018-08-19', postal_code: 6990623, street_address: '島根県出雲市大津2525', examination_hall: '出雲商業高校', examinees_count_man: 1, examinees_count_woman: 1, selection_method: 1, s_method_writing: true, s_method_appropriate: false, s_method_interview: false, s_method_composition: false, s_method_physical: false, t_subject_japanese: 50, writing_test_contents: '余裕です', other_coment: '頑張ってください', approval_flg: 1)
EtReport.create(reporting_date: '2015-09-24', student_class: 4, student_number: 13, student_id: 's20161415', job_category: '巫女', office_name: '出雲大社', introduction_number: 1, test_day: '2015-09-24', street_address: '出雲大社', examination_hall: '出雲大社　社務所内', selection_method: 1, s_method_writing: true, s_method_appropriate: false, s_method_interview: true, s_method_composition: true, s_method_physical: false, t_subject_japanese: 60, i_method_one: 1, judge_count: 3, i_time: 10, i_contents: '・いつから出雲大社で働きたいと思うようになったか。　・緊張しているか。　・作文で書いたことへの質問（作文から深くきかれる）　・成績表からへの質問　・巫女と販売する仕事は何が違うか。', composition_title: '志望動機', c_sheet_count: 2, writing_test_contents: '書き16問　・ヤクドシ　・ギオン祭り　・ノリト　・ハツモウデ　・シメナワ　・スウケイ　・ゾウエイ　・イセジングウ　・カンレキ　・イサン　・ハンジョウ　・ウジコ　・キッキョウ　・ブンカザイ　・コジキ　読み14問　・出雲大社　・神楽　・専ら　・繕う　・赴く　・廃れる　・練る　・否む　・境内　・御守り　・地鎮祭　・遷宮　・干支　・灯籠　全30問', other_coment: '自分のことをしっかりアピールすること。　緊張しすぎない！リラックスすること。　漢字はほぼ昨年のからでました。　神社に関する漢字を全部覚えておくこと。', approval_flg: 0)
EtReport.create(reporting_date: '2015-10-21', student_class: 4, student_number: 13, student_id: 's20161415', job_category: '製造業', office_name: 'オーエム金属工業株式会社', introduction_number: 1, test_day: '2015-10-21', street_address: '島根県松江市宍道町佐々布75番地', examination_hall: 'オーエム金属工業株式会社', examinees_count_man: 1, examinees_count_woman: 0, examinees_count_total: 0, selection_method: 1, s_method_writing: false, s_method_appropriate: false, s_method_interview: true, s_method_composition: false, s_method_physical: false, i_method_one: 1, judge_count: 4, i_time: 30, i_contents: '志望理由　休みの日にどんなことをしているか　学校生活で頑張ったこと　部活以外で好きなこととくいなこと　車で通勤するのか　大会で全国に出場するのはすごいことか　製造業をずっと考え続けて来たか　クラスは何クラスあるのか　最後になにか言いたいことはあるか', other_coment: '声は大きいほうが良い　挨拶はしっかりとしたほうが良い', approval_flg: 0)
