# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(user_id: 't201701', name: '吉村先生', password: '123', flg: 0, annual: 2017, authority: 1)
User.create(user_id: 's20161414', name: '野々村幸彦', password: '123', flg: 0, annual: 2016, authority: 2)
User.create(user_id: 's20161415', name: '樋野拓人', password: '123', flg: 0, annual: 2016, authority: 2)
User.create(user_id: 's20161406', name: '伊藤陸', password: '123', flg: 0, annual: 2016, authority: 2)
User.create(user_id: 'g2016', name: 'ゲストユーザー', password: '123', flg: 0, annual: 2016, authority: 3)

EeReport.create( reporting_date: '2017-10-17', student_class: 4, student_number: 12, student_id: 's20161414', school_name: '大阪成蹊短期大学', s_department_name: '幼児教育学科', test_day: '2017-10-14', street_address: '大阪府大阪市東淀川区相川 3-10-62', examination_hall: '大阪成蹊短期大学', result_publication_date: '2017-10-26', entrance_form: 2, recommended_group:2, r_self: true, recommended_form: 2, i_q_contents: '志望理由、入学して頑張りたいこと、大阪に来たことがあるか、当日、誰と来たか、商業高校からなぜ保育に道を選んだのか、一人暮らしで家庭学習時間をどのようにとるか、オープンキャンパスでは何をしたか（体験授業）', r_impression: '練習していないことも聞かれましたが、対応できました。', approval_flg: 0)
EeReport.create( reporting_date: '2017-12-11', student_class: 4, student_number: 12, student_id: 's20161414', school_name: '大阪健康福祉短期大学　松江キャンパス', s_department_name: '保育・幼児教育学科', test_day: '2017-12-09', street_address: '島根県松江市学園南1丁目15-10', examination_hall: '島根総合福祉専門学校 松江学園南キャンパス', result_publication_date: '2017-12-16', entrance_form: 2, recommended_group:2, r_self: true, recommended_form: 2, i_q_contents: '志望理由、なりたい保育士とその理由、事故PR、楽しかったこと、つらかったこととそれをどう乗り越えたか、気になったこと、印象に残っていることピアノの経験、不安なこと、「面接時間２０分」', r_impression: '面接官の方がうなずきながら聞いてくださったので、リラックスして質問に答えることができました。とても話しやすい雰囲気でした', approval_flg: 0)
EeReport.create( reporting_date: '2017-11-13', student_class: 4, student_number: 12, student_id: 's20161414', school_name: '大阪経済大学', s_faculty_name: '経済学部', s_department_name: '経済学科', test_day: '2017-11-11', street_address: '大阪府大阪市東淀川区大隅2-2-8', examination_hall: '大阪経済大学', result_publication_date: '2017-11-18', entrance_form: 2, recommended_group:2, r_self: true, recommended_form: '「書類選考」＋小論文＋試験', e_contents: '人間の離農を上回るAI(人口知能について)', w_contents: '新聞の記事「新風 Silicon Vaiiey AI開発 多様な視点で」の一部の文を要約する（300文字以内）、問題文を読み、人工知能（AI）全盛期はどのような社会になるのが人々にとって理想か、自分の考えを述べる。（500文字以内） d', r_impression: '小論文は先生から指導を受けたおかげで、困ることはありませんでした。しかし、商工系ということもあり工業系の知識がもう少し必要だと思いました。', approval_flg: 0)

EtReport.create(reporting_date: '2017-11-30', student_class: 4, student_number: 5, student_id: 's20161406', job_category: '営業職', office_name: '株式会社ファルコバイオシステムズ', job_vote_number: 2173, introduction_number: 1, test_day: '2017-11-30', street_address: '島根県出雲塩谷善行町12-2', examination_hall: 'ビックハート出雲', examinees_count_man: 0, examinees_count_woman: 1, selection_method: 1, s_method_writing: false, s_method_appropriate: false, s_method_interview: true, s_method_composition: false, s_method_physical: false, s_method_other: false, t_subject_general: 30, i_method_one: 1, judge_count: 2, i_time: 40, i_contents: '緊張はしているか？、部活動で学んだこと、自己アピール、コース選択について、体力はあるか、コミュニケーション能力はあるか、検定について、どのような内容か、クラスでどのくらいの割合が合格するか、好きな教科、出商デパートとは', writing_test_contents: '１から１００まで足すといくつ？、１６０ｇの食塩に６％の食塩水を１０ｇ混ぜた時、食塩水の濃度はいくつ、「腹心」の同類後は？３２人中Aさんは後から１０人目です。前から何人目？、日本が由来となった元素は？', approval_flg: 0)
EtReport.create(reporting_date: '2017-11-30', student_class: 4, student_number: 5, student_id: 's20161406', job_category: '薬局事務', office_name: 'ハーブ薬局', introduction_number: 1, test_day: '2017-11-30', street_address: '松江市本庄町531', examination_hall: 'ハーブ薬局', examinees_count_man: 0, examinees_count_woman: 1, selection_method: 1, s_method_writing: true, s_method_appropriate: false, s_method_interview: true, s_method_composition: true, s_method_physical: false, s_method_other: false, t_subject_japanese: 10, t_subject_math: 10, t_subject_other_name: '作文', t_subject_other_time: 10, i_method_one: 1, judge_count: 2, i_time: 10, i_contents: '志望動機、薬局で必要だと思う力を３つとその理由、病気などについて勉強するならどんな方法でするのか、自分が薬局に入ったらいかせること、休みの日には何をするか、何をして遊んでいるか、どんな話をしているか、友達と話して自分のためになると思うこと、本は読まれますか、カフェに行くことになり土日にシフトが入ることについて、体力には自信はあるか、これからの薬局について、質問はありますか', composition_title: '上司がミスをしていたらどうするのか', c_sheet_count: 1, writing_test_contents: '国語、漢字の読み書き、数学、簡単な計算問題（ルート、因数分解）、角度,確率、作文、例文のようなものがあって詳しいシチュエーションが書いてあり、それを読んでからなぜそう思うのかなぜそうしたら良いと、思うか書く。', other_coment: '筆記は基礎力が必要な問題でした。、時間が短いので焦らず問くといい。', approval_flg: 0)
EtReport.create(reporting_date: '2015-09-24', student_class: 4, student_number: 13, student_id: 's20161415', job_category: '巫女', office_name: '出雲大社', introduction_number: 1, test_day: '2015-09-24', street_address: '出雲大社', examination_hall: '出雲大社　社務所内', examinees_count_man: 0, examinees_count_woman: 1, selection_method: 1, s_method_writing: true, s_method_appropriate: false, s_method_interview: true, s_method_composition: true, s_method_physical: false, t_subject_japanese: 60, i_method_one: 1, judge_count: 3, i_time: 10, i_contents: '・いつから出雲大社で働きたいと思うようになったか。　・緊張しているか。　・作文で書いたことへの質問（作文から深くきかれる）　・成績表からへの質問　・巫女と販売する仕事は何が違うか。', composition_title: '志望動機', c_sheet_count: 2, writing_test_contents: '書き16問　・ヤクドシ　・ギオン祭り　・ノリト　・ハツモウデ　・シメナワ　・スウケイ　・ゾウエイ　・イセジングウ　・カンレキ　・イサン　・ハンジョウ　・ウジコ　・キッキョウ　・ブンカザイ　・コジキ　読み14問　・出雲大社　・神楽　・専ら　・繕う　・赴く　・廃れる　・練る　・否む　・境内　・御守り　・地鎮祭　・遷宮　・干支　・灯籠　全30問', other_coment: '自分のことをしっかりアピールすること。　緊張しすぎない！リラックスすること。　漢字はほぼ昨年のからでました。　神社に関する漢字を全部覚えておくこと。', approval_flg: 0)
EtReport.create(reporting_date: '2015-10-21', student_class: 4, student_number: 13, student_id: 's20161415', job_category: '製造業', office_name: 'オーエム金属工業株式会社', introduction_number: 1, test_day: '2015-10-21', street_address: '島根県松江市宍道町佐々布75番地', examination_hall: 'オーエム金属工業株式会社', examinees_count_man: 1, examinees_count_woman: 0, selection_method: 1, s_method_writing: false, s_method_appropriate: false, s_method_interview: true, s_method_composition: false, s_method_physical: false, i_method_one: 1, judge_count: 4, i_time: 30, i_contents: '志望理由　休みの日にどんなことをしているか　学校生活で頑張ったこと　部活以外で好きなこととくいなこと　車で通勤するのか　大会で全国に出場するのはすごいことか　製造業をずっと考え続けて来たか　クラスは何クラスあるのか　最後になにか言いたいことはあるか', other_coment: '声は大きいほうが良い　挨拶はしっかりとしたほうが良い', approval_flg: 0)
EtReport.create(reporting_date: '2015-09-24', student_class: 4, student_number: 13, student_id: 's20161415', job_category: '巫女', office_name: '出雲大社', job_vote_number: 2096, introduction_number: 1, test_day: '2015-09-24', postal_code: 6990701,street_address: '島根県出雲市大社町杵築東195', examination_hall: '出雲大社　社務所', examinees_count_man: 0, examinees_count_woman: 10, selection_method: 1, s_method_writing: true, s_method_appropriate: false, s_method_interview: true, s_method_composition: true, s_method_physical: false, t_subject_japanese: 60, i_method_one: 1, judge_count: 2, i_time: 15, i_contents: '作文、履歴書のことについて　・志望動機・人と関わることについて興味をもったきっかけ・普通の接客と神社等の接客の違いとは何か・巫女についてどう感じているか・吹奏楽のことについて（部活）・楽器は何か・全国大会について・皆勤だが気をつけていることはあるか', composition_title: '志望動機', c_sheet_count: 2, writing_test_contents: '国語（漢字）小テスト　（全部で約30問くらい)　書き(約15問）　・ヤクドシ　・イセジングウ　・キッキョウ　・ウジコ　・ハツモウデ　・コジキ　・スウケイ　・イサン　・ブンカザイ　・ギオン　・ノリト　・ゾウエイ　・シメナワ　・カンレキ　・ハンジョウ　読み（約14問）　・出雲大社　・繕う　・神楽　・境内　・遷宮　・灯籠　・専ら　・廃れた　・地鎮祭　・御守り　・干支　・否む　・練る　・赴く', other_coment: '面接　　とても雰囲気がよかった。面談みたいな感じだったのでリラックスすれは、いつも通りにすることができました。入退室も気を抜かないようにしたらいいと思いました。漢字・作文　　少ししか問題数はなかったですが、一問一問がとても難しいので、細いところまで(とめ、はね）練習しておくといいと思います。あと、ここに残っていない漢字も知っておくといいと思います。作文は毎年テーマは変わらないので、練習しておくといいと思います。', approval_flg: 0)